package mdatum.udc.com.m_datum.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CULTIVO".
*/
public class CultivoDao extends AbstractDao<Cultivo, Long> {

    public static final String TABLENAME = "CULTIVO";

    /**
     * Properties of entity Cultivo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EspecieId = new Property(1, int.class, "especieId", false, "ESPECIE_ID");
        public final static Property TipoId = new Property(2, int.class, "tipoId", false, "TIPO_ID");
        public final static Property NroSiembra = new Property(3, int.class, "nroSiembra", false, "NRO_SIEMBRA");
        public final static Property MesSiembra = new Property(4, int.class, "mesSiembra", false, "MES_SIEMBRA");
        public final static Property Surcos = new Property(5, int.class, "surcos", false, "SURCOS");
        public final static Property Distancias = new Property(6, int.class, "distancias", false, "DISTANCIAS");
        public final static Property Largo = new Property(7, int.class, "largo", false, "LARGO");
        public final static Property SuperficieSembrada = new Property(8, int.class, "superficieSembrada", false, "SUPERFICIE_SEMBRADA");
        public final static Property SuperficieMedidaId = new Property(9, int.class, "superficieMedidaId", false, "SUPERFICIE_MEDIDA_ID");
        public final static Property TipoProduccionId = new Property(10, int.class, "tipoProduccionId", false, "TIPO_PRODUCCION_ID");
        public final static Property EleccionCultivoId = new Property(11, int.class, "eleccionCultivoId", false, "ELECCION_CULTIVO_ID");
        public final static Property EleccionEspecificar = new Property(12, String.class, "eleccionEspecificar", false, "ELECCION_ESPECIFICAR");
    }


    public CultivoDao(DaoConfig config) {
        super(config);
    }
    
    public CultivoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CULTIVO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ESPECIE_ID\" INTEGER NOT NULL ," + // 1: especieId
                "\"TIPO_ID\" INTEGER NOT NULL ," + // 2: tipoId
                "\"NRO_SIEMBRA\" INTEGER NOT NULL ," + // 3: nroSiembra
                "\"MES_SIEMBRA\" INTEGER NOT NULL ," + // 4: mesSiembra
                "\"SURCOS\" INTEGER NOT NULL ," + // 5: surcos
                "\"DISTANCIAS\" INTEGER NOT NULL ," + // 6: distancias
                "\"LARGO\" INTEGER NOT NULL ," + // 7: largo
                "\"SUPERFICIE_SEMBRADA\" INTEGER NOT NULL ," + // 8: superficieSembrada
                "\"SUPERFICIE_MEDIDA_ID\" INTEGER NOT NULL ," + // 9: superficieMedidaId
                "\"TIPO_PRODUCCION_ID\" INTEGER NOT NULL ," + // 10: tipoProduccionId
                "\"ELECCION_CULTIVO_ID\" INTEGER NOT NULL ," + // 11: eleccionCultivoId
                "\"ELECCION_ESPECIFICAR\" TEXT);"); // 12: eleccionEspecificar
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CULTIVO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Cultivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEspecieId());
        stmt.bindLong(3, entity.getTipoId());
        stmt.bindLong(4, entity.getNroSiembra());
        stmt.bindLong(5, entity.getMesSiembra());
        stmt.bindLong(6, entity.getSurcos());
        stmt.bindLong(7, entity.getDistancias());
        stmt.bindLong(8, entity.getLargo());
        stmt.bindLong(9, entity.getSuperficieSembrada());
        stmt.bindLong(10, entity.getSuperficieMedidaId());
        stmt.bindLong(11, entity.getTipoProduccionId());
        stmt.bindLong(12, entity.getEleccionCultivoId());
 
        String eleccionEspecificar = entity.getEleccionEspecificar();
        if (eleccionEspecificar != null) {
            stmt.bindString(13, eleccionEspecificar);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Cultivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEspecieId());
        stmt.bindLong(3, entity.getTipoId());
        stmt.bindLong(4, entity.getNroSiembra());
        stmt.bindLong(5, entity.getMesSiembra());
        stmt.bindLong(6, entity.getSurcos());
        stmt.bindLong(7, entity.getDistancias());
        stmt.bindLong(8, entity.getLargo());
        stmt.bindLong(9, entity.getSuperficieSembrada());
        stmt.bindLong(10, entity.getSuperficieMedidaId());
        stmt.bindLong(11, entity.getTipoProduccionId());
        stmt.bindLong(12, entity.getEleccionCultivoId());
 
        String eleccionEspecificar = entity.getEleccionEspecificar();
        if (eleccionEspecificar != null) {
            stmt.bindString(13, eleccionEspecificar);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Cultivo readEntity(Cursor cursor, int offset) {
        Cultivo entity = new Cultivo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // especieId
            cursor.getInt(offset + 2), // tipoId
            cursor.getInt(offset + 3), // nroSiembra
            cursor.getInt(offset + 4), // mesSiembra
            cursor.getInt(offset + 5), // surcos
            cursor.getInt(offset + 6), // distancias
            cursor.getInt(offset + 7), // largo
            cursor.getInt(offset + 8), // superficieSembrada
            cursor.getInt(offset + 9), // superficieMedidaId
            cursor.getInt(offset + 10), // tipoProduccionId
            cursor.getInt(offset + 11), // eleccionCultivoId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // eleccionEspecificar
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Cultivo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEspecieId(cursor.getInt(offset + 1));
        entity.setTipoId(cursor.getInt(offset + 2));
        entity.setNroSiembra(cursor.getInt(offset + 3));
        entity.setMesSiembra(cursor.getInt(offset + 4));
        entity.setSurcos(cursor.getInt(offset + 5));
        entity.setDistancias(cursor.getInt(offset + 6));
        entity.setLargo(cursor.getInt(offset + 7));
        entity.setSuperficieSembrada(cursor.getInt(offset + 8));
        entity.setSuperficieMedidaId(cursor.getInt(offset + 9));
        entity.setTipoProduccionId(cursor.getInt(offset + 10));
        entity.setEleccionCultivoId(cursor.getInt(offset + 11));
        entity.setEleccionEspecificar(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Cultivo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Cultivo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Cultivo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
