package mdatum.udc.com.m_datum.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mdatum.udc.com.m_datum.database.Establecimiento;
import mdatum.udc.com.m_datum.database.RegimenTenencia;
import mdatum.udc.com.m_datum.database.Encuestado;
import mdatum.udc.com.m_datum.database.NivelInstruccion;
import mdatum.udc.com.m_datum.database.Nacionalidad;
import mdatum.udc.com.m_datum.database.Familia;
import mdatum.udc.com.m_datum.database.AnioEstructura;
import mdatum.udc.com.m_datum.database.MaterialEstructura;
import mdatum.udc.com.m_datum.database.Invernaculo;
import mdatum.udc.com.m_datum.database.Cultivo;
import mdatum.udc.com.m_datum.database.EleccionCultivo;
import mdatum.udc.com.m_datum.database.Especie;
import mdatum.udc.com.m_datum.database.TipoCultivo;
import mdatum.udc.com.m_datum.database.TipoProduccion;
import mdatum.udc.com.m_datum.database.FactorClimatico;
import mdatum.udc.com.m_datum.database.Asesoramiento;
import mdatum.udc.com.m_datum.database.TripleLavado;
import mdatum.udc.com.m_datum.database.Agroquimicos;
import mdatum.udc.com.m_datum.database.Encuesta;
import mdatum.udc.com.m_datum.database.EncuestaInvernaculo;
import mdatum.udc.com.m_datum.database.EncuestaCultivo;
import mdatum.udc.com.m_datum.database.AgroquimicoUsado;
import mdatum.udc.com.m_datum.database.EncuestaAgroquimicoUsado;

import mdatum.udc.com.m_datum.database.EstablecimientoDao;
import mdatum.udc.com.m_datum.database.RegimenTenenciaDao;
import mdatum.udc.com.m_datum.database.EncuestadoDao;
import mdatum.udc.com.m_datum.database.NivelInstruccionDao;
import mdatum.udc.com.m_datum.database.NacionalidadDao;
import mdatum.udc.com.m_datum.database.FamiliaDao;
import mdatum.udc.com.m_datum.database.AnioEstructuraDao;
import mdatum.udc.com.m_datum.database.MaterialEstructuraDao;
import mdatum.udc.com.m_datum.database.InvernaculoDao;
import mdatum.udc.com.m_datum.database.CultivoDao;
import mdatum.udc.com.m_datum.database.EleccionCultivoDao;
import mdatum.udc.com.m_datum.database.EspecieDao;
import mdatum.udc.com.m_datum.database.TipoCultivoDao;
import mdatum.udc.com.m_datum.database.TipoProduccionDao;
import mdatum.udc.com.m_datum.database.FactorClimaticoDao;
import mdatum.udc.com.m_datum.database.AsesoramientoDao;
import mdatum.udc.com.m_datum.database.TripleLavadoDao;
import mdatum.udc.com.m_datum.database.AgroquimicosDao;
import mdatum.udc.com.m_datum.database.EncuestaDao;
import mdatum.udc.com.m_datum.database.EncuestaInvernaculoDao;
import mdatum.udc.com.m_datum.database.EncuestaCultivoDao;
import mdatum.udc.com.m_datum.database.AgroquimicoUsadoDao;
import mdatum.udc.com.m_datum.database.EncuestaAgroquimicoUsadoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig establecimientoDaoConfig;
    private final DaoConfig regimenTenenciaDaoConfig;
    private final DaoConfig encuestadoDaoConfig;
    private final DaoConfig nivelInstruccionDaoConfig;
    private final DaoConfig nacionalidadDaoConfig;
    private final DaoConfig familiaDaoConfig;
    private final DaoConfig anioEstructuraDaoConfig;
    private final DaoConfig materialEstructuraDaoConfig;
    private final DaoConfig invernaculoDaoConfig;
    private final DaoConfig cultivoDaoConfig;
    private final DaoConfig eleccionCultivoDaoConfig;
    private final DaoConfig especieDaoConfig;
    private final DaoConfig tipoCultivoDaoConfig;
    private final DaoConfig tipoProduccionDaoConfig;
    private final DaoConfig factorClimaticoDaoConfig;
    private final DaoConfig asesoramientoDaoConfig;
    private final DaoConfig tripleLavadoDaoConfig;
    private final DaoConfig agroquimicosDaoConfig;
    private final DaoConfig encuestaDaoConfig;
    private final DaoConfig encuestaInvernaculoDaoConfig;
    private final DaoConfig encuestaCultivoDaoConfig;
    private final DaoConfig agroquimicoUsadoDaoConfig;
    private final DaoConfig encuestaAgroquimicoUsadoDaoConfig;

    private final EstablecimientoDao establecimientoDao;
    private final RegimenTenenciaDao regimenTenenciaDao;
    private final EncuestadoDao encuestadoDao;
    private final NivelInstruccionDao nivelInstruccionDao;
    private final NacionalidadDao nacionalidadDao;
    private final FamiliaDao familiaDao;
    private final AnioEstructuraDao anioEstructuraDao;
    private final MaterialEstructuraDao materialEstructuraDao;
    private final InvernaculoDao invernaculoDao;
    private final CultivoDao cultivoDao;
    private final EleccionCultivoDao eleccionCultivoDao;
    private final EspecieDao especieDao;
    private final TipoCultivoDao tipoCultivoDao;
    private final TipoProduccionDao tipoProduccionDao;
    private final FactorClimaticoDao factorClimaticoDao;
    private final AsesoramientoDao asesoramientoDao;
    private final TripleLavadoDao tripleLavadoDao;
    private final AgroquimicosDao agroquimicosDao;
    private final EncuestaDao encuestaDao;
    private final EncuestaInvernaculoDao encuestaInvernaculoDao;
    private final EncuestaCultivoDao encuestaCultivoDao;
    private final AgroquimicoUsadoDao agroquimicoUsadoDao;
    private final EncuestaAgroquimicoUsadoDao encuestaAgroquimicoUsadoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        establecimientoDaoConfig = daoConfigMap.get(EstablecimientoDao.class).clone();
        establecimientoDaoConfig.initIdentityScope(type);

        regimenTenenciaDaoConfig = daoConfigMap.get(RegimenTenenciaDao.class).clone();
        regimenTenenciaDaoConfig.initIdentityScope(type);

        encuestadoDaoConfig = daoConfigMap.get(EncuestadoDao.class).clone();
        encuestadoDaoConfig.initIdentityScope(type);

        nivelInstruccionDaoConfig = daoConfigMap.get(NivelInstruccionDao.class).clone();
        nivelInstruccionDaoConfig.initIdentityScope(type);

        nacionalidadDaoConfig = daoConfigMap.get(NacionalidadDao.class).clone();
        nacionalidadDaoConfig.initIdentityScope(type);

        familiaDaoConfig = daoConfigMap.get(FamiliaDao.class).clone();
        familiaDaoConfig.initIdentityScope(type);

        anioEstructuraDaoConfig = daoConfigMap.get(AnioEstructuraDao.class).clone();
        anioEstructuraDaoConfig.initIdentityScope(type);

        materialEstructuraDaoConfig = daoConfigMap.get(MaterialEstructuraDao.class).clone();
        materialEstructuraDaoConfig.initIdentityScope(type);

        invernaculoDaoConfig = daoConfigMap.get(InvernaculoDao.class).clone();
        invernaculoDaoConfig.initIdentityScope(type);

        cultivoDaoConfig = daoConfigMap.get(CultivoDao.class).clone();
        cultivoDaoConfig.initIdentityScope(type);

        eleccionCultivoDaoConfig = daoConfigMap.get(EleccionCultivoDao.class).clone();
        eleccionCultivoDaoConfig.initIdentityScope(type);

        especieDaoConfig = daoConfigMap.get(EspecieDao.class).clone();
        especieDaoConfig.initIdentityScope(type);

        tipoCultivoDaoConfig = daoConfigMap.get(TipoCultivoDao.class).clone();
        tipoCultivoDaoConfig.initIdentityScope(type);

        tipoProduccionDaoConfig = daoConfigMap.get(TipoProduccionDao.class).clone();
        tipoProduccionDaoConfig.initIdentityScope(type);

        factorClimaticoDaoConfig = daoConfigMap.get(FactorClimaticoDao.class).clone();
        factorClimaticoDaoConfig.initIdentityScope(type);

        asesoramientoDaoConfig = daoConfigMap.get(AsesoramientoDao.class).clone();
        asesoramientoDaoConfig.initIdentityScope(type);

        tripleLavadoDaoConfig = daoConfigMap.get(TripleLavadoDao.class).clone();
        tripleLavadoDaoConfig.initIdentityScope(type);

        agroquimicosDaoConfig = daoConfigMap.get(AgroquimicosDao.class).clone();
        agroquimicosDaoConfig.initIdentityScope(type);

        encuestaDaoConfig = daoConfigMap.get(EncuestaDao.class).clone();
        encuestaDaoConfig.initIdentityScope(type);

        encuestaInvernaculoDaoConfig = daoConfigMap.get(EncuestaInvernaculoDao.class).clone();
        encuestaInvernaculoDaoConfig.initIdentityScope(type);

        encuestaCultivoDaoConfig = daoConfigMap.get(EncuestaCultivoDao.class).clone();
        encuestaCultivoDaoConfig.initIdentityScope(type);

        agroquimicoUsadoDaoConfig = daoConfigMap.get(AgroquimicoUsadoDao.class).clone();
        agroquimicoUsadoDaoConfig.initIdentityScope(type);

        encuestaAgroquimicoUsadoDaoConfig = daoConfigMap.get(EncuestaAgroquimicoUsadoDao.class).clone();
        encuestaAgroquimicoUsadoDaoConfig.initIdentityScope(type);

        establecimientoDao = new EstablecimientoDao(establecimientoDaoConfig, this);
        regimenTenenciaDao = new RegimenTenenciaDao(regimenTenenciaDaoConfig, this);
        encuestadoDao = new EncuestadoDao(encuestadoDaoConfig, this);
        nivelInstruccionDao = new NivelInstruccionDao(nivelInstruccionDaoConfig, this);
        nacionalidadDao = new NacionalidadDao(nacionalidadDaoConfig, this);
        familiaDao = new FamiliaDao(familiaDaoConfig, this);
        anioEstructuraDao = new AnioEstructuraDao(anioEstructuraDaoConfig, this);
        materialEstructuraDao = new MaterialEstructuraDao(materialEstructuraDaoConfig, this);
        invernaculoDao = new InvernaculoDao(invernaculoDaoConfig, this);
        cultivoDao = new CultivoDao(cultivoDaoConfig, this);
        eleccionCultivoDao = new EleccionCultivoDao(eleccionCultivoDaoConfig, this);
        especieDao = new EspecieDao(especieDaoConfig, this);
        tipoCultivoDao = new TipoCultivoDao(tipoCultivoDaoConfig, this);
        tipoProduccionDao = new TipoProduccionDao(tipoProduccionDaoConfig, this);
        factorClimaticoDao = new FactorClimaticoDao(factorClimaticoDaoConfig, this);
        asesoramientoDao = new AsesoramientoDao(asesoramientoDaoConfig, this);
        tripleLavadoDao = new TripleLavadoDao(tripleLavadoDaoConfig, this);
        agroquimicosDao = new AgroquimicosDao(agroquimicosDaoConfig, this);
        encuestaDao = new EncuestaDao(encuestaDaoConfig, this);
        encuestaInvernaculoDao = new EncuestaInvernaculoDao(encuestaInvernaculoDaoConfig, this);
        encuestaCultivoDao = new EncuestaCultivoDao(encuestaCultivoDaoConfig, this);
        agroquimicoUsadoDao = new AgroquimicoUsadoDao(agroquimicoUsadoDaoConfig, this);
        encuestaAgroquimicoUsadoDao = new EncuestaAgroquimicoUsadoDao(encuestaAgroquimicoUsadoDaoConfig, this);

        registerDao(Establecimiento.class, establecimientoDao);
        registerDao(RegimenTenencia.class, regimenTenenciaDao);
        registerDao(Encuestado.class, encuestadoDao);
        registerDao(NivelInstruccion.class, nivelInstruccionDao);
        registerDao(Nacionalidad.class, nacionalidadDao);
        registerDao(Familia.class, familiaDao);
        registerDao(AnioEstructura.class, anioEstructuraDao);
        registerDao(MaterialEstructura.class, materialEstructuraDao);
        registerDao(Invernaculo.class, invernaculoDao);
        registerDao(Cultivo.class, cultivoDao);
        registerDao(EleccionCultivo.class, eleccionCultivoDao);
        registerDao(Especie.class, especieDao);
        registerDao(TipoCultivo.class, tipoCultivoDao);
        registerDao(TipoProduccion.class, tipoProduccionDao);
        registerDao(FactorClimatico.class, factorClimaticoDao);
        registerDao(Asesoramiento.class, asesoramientoDao);
        registerDao(TripleLavado.class, tripleLavadoDao);
        registerDao(Agroquimicos.class, agroquimicosDao);
        registerDao(Encuesta.class, encuestaDao);
        registerDao(EncuestaInvernaculo.class, encuestaInvernaculoDao);
        registerDao(EncuestaCultivo.class, encuestaCultivoDao);
        registerDao(AgroquimicoUsado.class, agroquimicoUsadoDao);
        registerDao(EncuestaAgroquimicoUsado.class, encuestaAgroquimicoUsadoDao);
    }
    
    public void clear() {
        establecimientoDaoConfig.clearIdentityScope();
        regimenTenenciaDaoConfig.clearIdentityScope();
        encuestadoDaoConfig.clearIdentityScope();
        nivelInstruccionDaoConfig.clearIdentityScope();
        nacionalidadDaoConfig.clearIdentityScope();
        familiaDaoConfig.clearIdentityScope();
        anioEstructuraDaoConfig.clearIdentityScope();
        materialEstructuraDaoConfig.clearIdentityScope();
        invernaculoDaoConfig.clearIdentityScope();
        cultivoDaoConfig.clearIdentityScope();
        eleccionCultivoDaoConfig.clearIdentityScope();
        especieDaoConfig.clearIdentityScope();
        tipoCultivoDaoConfig.clearIdentityScope();
        tipoProduccionDaoConfig.clearIdentityScope();
        factorClimaticoDaoConfig.clearIdentityScope();
        asesoramientoDaoConfig.clearIdentityScope();
        tripleLavadoDaoConfig.clearIdentityScope();
        agroquimicosDaoConfig.clearIdentityScope();
        encuestaDaoConfig.clearIdentityScope();
        encuestaInvernaculoDaoConfig.clearIdentityScope();
        encuestaCultivoDaoConfig.clearIdentityScope();
        agroquimicoUsadoDaoConfig.clearIdentityScope();
        encuestaAgroquimicoUsadoDaoConfig.clearIdentityScope();
    }

    public EstablecimientoDao getEstablecimientoDao() {
        return establecimientoDao;
    }

    public RegimenTenenciaDao getRegimenTenenciaDao() {
        return regimenTenenciaDao;
    }

    public EncuestadoDao getEncuestadoDao() {
        return encuestadoDao;
    }

    public NivelInstruccionDao getNivelInstruccionDao() {
        return nivelInstruccionDao;
    }

    public NacionalidadDao getNacionalidadDao() {
        return nacionalidadDao;
    }

    public FamiliaDao getFamiliaDao() {
        return familiaDao;
    }

    public AnioEstructuraDao getAnioEstructuraDao() {
        return anioEstructuraDao;
    }

    public MaterialEstructuraDao getMaterialEstructuraDao() {
        return materialEstructuraDao;
    }

    public InvernaculoDao getInvernaculoDao() {
        return invernaculoDao;
    }

    public CultivoDao getCultivoDao() {
        return cultivoDao;
    }

    public EleccionCultivoDao getEleccionCultivoDao() {
        return eleccionCultivoDao;
    }

    public EspecieDao getEspecieDao() {
        return especieDao;
    }

    public TipoCultivoDao getTipoCultivoDao() {
        return tipoCultivoDao;
    }

    public TipoProduccionDao getTipoProduccionDao() {
        return tipoProduccionDao;
    }

    public FactorClimaticoDao getFactorClimaticoDao() {
        return factorClimaticoDao;
    }

    public AsesoramientoDao getAsesoramientoDao() {
        return asesoramientoDao;
    }

    public TripleLavadoDao getTripleLavadoDao() {
        return tripleLavadoDao;
    }

    public AgroquimicosDao getAgroquimicosDao() {
        return agroquimicosDao;
    }

    public EncuestaDao getEncuestaDao() {
        return encuestaDao;
    }

    public EncuestaInvernaculoDao getEncuestaInvernaculoDao() {
        return encuestaInvernaculoDao;
    }

    public EncuestaCultivoDao getEncuestaCultivoDao() {
        return encuestaCultivoDao;
    }

    public AgroquimicoUsadoDao getAgroquimicoUsadoDao() {
        return agroquimicoUsadoDao;
    }

    public EncuestaAgroquimicoUsadoDao getEncuestaAgroquimicoUsadoDao() {
        return encuestaAgroquimicoUsadoDao;
    }

}
