package mdatum.udc.com.m_datum.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import mdatum.udc.com.m_datum.database.Establecimiento;
import mdatum.udc.com.m_datum.database.RegimenTenencia;
import mdatum.udc.com.m_datum.database.Encuestado;
import mdatum.udc.com.m_datum.database.NivelInstruccion;
import mdatum.udc.com.m_datum.database.Nacionalidad;
import mdatum.udc.com.m_datum.database.Familia;

import mdatum.udc.com.m_datum.database.EstablecimientoDao;
import mdatum.udc.com.m_datum.database.RegimenTenenciaDao;
import mdatum.udc.com.m_datum.database.EncuestadoDao;
import mdatum.udc.com.m_datum.database.NivelInstruccionDao;
import mdatum.udc.com.m_datum.database.NacionalidadDao;
import mdatum.udc.com.m_datum.database.FamiliaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig establecimientoDaoConfig;
    private final DaoConfig regimenTenenciaDaoConfig;
    private final DaoConfig encuestadoDaoConfig;
    private final DaoConfig nivelInstruccionDaoConfig;
    private final DaoConfig nacionalidadDaoConfig;
    private final DaoConfig familiaDaoConfig;

    private final EstablecimientoDao establecimientoDao;
    private final RegimenTenenciaDao regimenTenenciaDao;
    private final EncuestadoDao encuestadoDao;
    private final NivelInstruccionDao nivelInstruccionDao;
    private final NacionalidadDao nacionalidadDao;
    private final FamiliaDao familiaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        establecimientoDaoConfig = daoConfigMap.get(EstablecimientoDao.class).clone();
        establecimientoDaoConfig.initIdentityScope(type);

        regimenTenenciaDaoConfig = daoConfigMap.get(RegimenTenenciaDao.class).clone();
        regimenTenenciaDaoConfig.initIdentityScope(type);

        encuestadoDaoConfig = daoConfigMap.get(EncuestadoDao.class).clone();
        encuestadoDaoConfig.initIdentityScope(type);

        nivelInstruccionDaoConfig = daoConfigMap.get(NivelInstruccionDao.class).clone();
        nivelInstruccionDaoConfig.initIdentityScope(type);

        nacionalidadDaoConfig = daoConfigMap.get(NacionalidadDao.class).clone();
        nacionalidadDaoConfig.initIdentityScope(type);

        familiaDaoConfig = daoConfigMap.get(FamiliaDao.class).clone();
        familiaDaoConfig.initIdentityScope(type);

        establecimientoDao = new EstablecimientoDao(establecimientoDaoConfig, this);
        regimenTenenciaDao = new RegimenTenenciaDao(regimenTenenciaDaoConfig, this);
        encuestadoDao = new EncuestadoDao(encuestadoDaoConfig, this);
        nivelInstruccionDao = new NivelInstruccionDao(nivelInstruccionDaoConfig, this);
        nacionalidadDao = new NacionalidadDao(nacionalidadDaoConfig, this);
        familiaDao = new FamiliaDao(familiaDaoConfig, this);

        registerDao(Establecimiento.class, establecimientoDao);
        registerDao(RegimenTenencia.class, regimenTenenciaDao);
        registerDao(Encuestado.class, encuestadoDao);
        registerDao(NivelInstruccion.class, nivelInstruccionDao);
        registerDao(Nacionalidad.class, nacionalidadDao);
        registerDao(Familia.class, familiaDao);
    }
    
    public void clear() {
        establecimientoDaoConfig.clearIdentityScope();
        regimenTenenciaDaoConfig.clearIdentityScope();
        encuestadoDaoConfig.clearIdentityScope();
        nivelInstruccionDaoConfig.clearIdentityScope();
        nacionalidadDaoConfig.clearIdentityScope();
        familiaDaoConfig.clearIdentityScope();
    }

    public EstablecimientoDao getEstablecimientoDao() {
        return establecimientoDao;
    }

    public RegimenTenenciaDao getRegimenTenenciaDao() {
        return regimenTenenciaDao;
    }

    public EncuestadoDao getEncuestadoDao() {
        return encuestadoDao;
    }

    public NivelInstruccionDao getNivelInstruccionDao() {
        return nivelInstruccionDao;
    }

    public NacionalidadDao getNacionalidadDao() {
        return nacionalidadDao;
    }

    public FamiliaDao getFamiliaDao() {
        return familiaDao;
    }

}
