package mdatum.udc.com.m_datum.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ENCUESTA_AGROQUIMICO_USADO".
*/
public class EncuestaAgroquimicoUsadoDao extends AbstractDao<EncuestaAgroquimicoUsado, Long> {

    public static final String TABLENAME = "ENCUESTA_AGROQUIMICO_USADO";

    /**
     * Properties of entity EncuestaAgroquimicoUsado.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdEncuesta = new Property(1, Long.class, "idEncuesta", false, "ID_ENCUESTA");
        public final static Property IdAgroquimicoUsado = new Property(2, Long.class, "idAgroquimicoUsado", false, "ID_AGROQUIMICO_USADO");
    }


    public EncuestaAgroquimicoUsadoDao(DaoConfig config) {
        super(config);
    }
    
    public EncuestaAgroquimicoUsadoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ENCUESTA_AGROQUIMICO_USADO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ID_ENCUESTA\" INTEGER," + // 1: idEncuesta
                "\"ID_AGROQUIMICO_USADO\" INTEGER);"); // 2: idAgroquimicoUsado
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ENCUESTA_AGROQUIMICO_USADO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EncuestaAgroquimicoUsado entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idEncuesta = entity.getIdEncuesta();
        if (idEncuesta != null) {
            stmt.bindLong(2, idEncuesta);
        }
 
        Long idAgroquimicoUsado = entity.getIdAgroquimicoUsado();
        if (idAgroquimicoUsado != null) {
            stmt.bindLong(3, idAgroquimicoUsado);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EncuestaAgroquimicoUsado entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long idEncuesta = entity.getIdEncuesta();
        if (idEncuesta != null) {
            stmt.bindLong(2, idEncuesta);
        }
 
        Long idAgroquimicoUsado = entity.getIdAgroquimicoUsado();
        if (idAgroquimicoUsado != null) {
            stmt.bindLong(3, idAgroquimicoUsado);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EncuestaAgroquimicoUsado readEntity(Cursor cursor, int offset) {
        EncuestaAgroquimicoUsado entity = new EncuestaAgroquimicoUsado( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // idEncuesta
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // idAgroquimicoUsado
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EncuestaAgroquimicoUsado entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdEncuesta(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdAgroquimicoUsado(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EncuestaAgroquimicoUsado entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EncuestaAgroquimicoUsado entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EncuestaAgroquimicoUsado entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
