package mdatum.udc.com.m_datum.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRANSACCION".
*/
public class TransaccionDao extends AbstractDao<Transaccion, Long> {

    public static final String TABLENAME = "TRANSACCION";

    /**
     * Properties of entity Transaccion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property EncuestaId = new Property(1, long.class, "encuestaId", false, "ENCUESTA_ID");
        public final static Property Transaccion = new Property(2, String.class, "transaccion", false, "TRANSACCION");
    }

    private DaoSession daoSession;


    public TransaccionDao(DaoConfig config) {
        super(config);
    }
    
    public TransaccionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRANSACCION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"ENCUESTA_ID\" INTEGER NOT NULL ," + // 1: encuestaId
                "\"TRANSACCION\" TEXT);"); // 2: transaccion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRANSACCION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Transaccion entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getEncuestaId());
 
        String transaccion = entity.getTransaccion();
        if (transaccion != null) {
            stmt.bindString(3, transaccion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Transaccion entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getEncuestaId());
 
        String transaccion = entity.getTransaccion();
        if (transaccion != null) {
            stmt.bindString(3, transaccion);
        }
    }

    @Override
    protected final void attachEntity(Transaccion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Transaccion readEntity(Cursor cursor, int offset) {
        Transaccion entity = new Transaccion( //
            cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // encuestaId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // transaccion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Transaccion entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setEncuestaId(cursor.getLong(offset + 1));
        entity.setTransaccion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Transaccion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Transaccion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Transaccion entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEncuestaDao().getAllColumns());
            builder.append(" FROM TRANSACCION T");
            builder.append(" LEFT JOIN ENCUESTA T0 ON T.\"ENCUESTA_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Transaccion loadCurrentDeep(Cursor cursor, boolean lock) {
        Transaccion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Encuesta encuesta = loadCurrentOther(daoSession.getEncuestaDao(), cursor, offset);
         if(encuesta != null) {
            entity.setEncuesta(encuesta);
        }

        return entity;    
    }

    public Transaccion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Transaccion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Transaccion> list = new ArrayList<Transaccion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Transaccion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Transaccion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
